<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ISE.DecisionOrchestration/ISE.DecisionOrchestration.csproj" />
    <ProjectReference Include="../ISE.Execution/ISE.Execution.csproj" />
    <ProjectReference Include="../ISE.InstitutionalDecisionEngine/ISE.InstitutionalDecisionEngine.csproj" />
    <ProjectReference Include="../ISE.PositionSizingIntelligence/ISE.PositionSizingIntelligence.csproj" />
    <ProjectReference Include="../ISE.ExecutionOrchestrator/ISE.ExecutionOrchestrator.csproj" />
    <ProjectReference Include="../ISE.TradeStateIntelligence/ISE.TradeStateIntelligence.csproj" />
    <ProjectReference Include="../ISE.TradeManagementIntelligence/ISE.TradeManagementIntelligence.csproj" />
  </ItemGroup>
</Project>
