<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ISE.Core\ISE.Core.csproj" />
    <ProjectReference Include="..\ISE.UnifiedRegimeEngine\ISE.UnifiedRegimeEngine.csproj" />
  </ItemGroup>

</Project>
