<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BacktestConsole</AssemblyName>
    <RootNamespace>ISE.BacktestTools</RootNamespace>
    <StartupObject>ISE.BacktestTools.Program</StartupObject>
    <DefaultItemExcludes>$(DefaultItemExcludes);ISE.HistoricalResearch.DatasetValidator/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/ISE.BacktestHarness/ISE.BacktestHarness.csproj" />
    <ProjectReference Include="../src/ISE.HistoricalResearch/ISE.HistoricalResearch.csproj" />
  </ItemGroup>

</Project>
