<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>UnifiedSystemTester</AssemblyName>
    <RootNamespace>ISE.BacktestTools</RootNamespace>
    <StartupObject>ISE.BacktestTools.UnifiedSystemTester</StartupObject>
    <DefaultItemExcludes>$(DefaultItemExcludes);BacktestConsole.cs;StrategyTester.cs</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/ISE.HistoricalResearch/ISE.HistoricalResearch.csproj" />
  </ItemGroup>

</Project>
